baseURL="https://polodev.github.io/ms/"
relativeurls = false
languageCode = "en-us"
publishDir="docs"
title = "This Site"
disqusShortname = "dev-learning"
[permalinks]
  post= "/:title/"
  tutorials= "/:title/"
  bits= "/:title/"
[params]
  afterDomain='ms'
  site_title = "polodev"
  site_description = "Learning With Ease"
[taxonomies]
  category="categories"
  tag="tags"
  author="authors"
  tutorial_tag="tutorial_tags"
  bit_tags="bit_tags"
  series="series"
  software="softwares"
  skill_level="skill_levels"
  tutorialType="tutorialTypes"
  [outputs]
home = [ "HTML", "RSS", "JSON"]
[menu]
  [[menu.main]]
    identifier = "tutorials"
    title = "Tutorials"
    url = "/tutorials/"
    weight = 1
  [[menu.main]]
    identifier = "bits"
    title = "Bits"
    url = "/bits/"
    weight = 2
  [[menu.main]]
    identifier = "sitemap"
    name = "sitemap"
    title = "Sitemap"
    url = "/sitemap/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "this is about page"
    title = "About"
    url = "/about/"
    weight = 99

[related]

# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
threshold = 0

# To get stable "See also" sections we, by default, exclude newer related pages.
includeNewer = true

# Will lower case keywords in both queries and in the indexes.
toLower = false

[[related.indices]]
name = "keyword"
weight = 100
[[related.indices]]
name  = "author"
toLower = true
weight = 10
[[related.indices]]
name  = "tutorialTypes"
weight = 50

