baseURL="https://polodev.github.io/ms/"
relativeurls = false
languageCode = "en-us"
publishDir="docs"
title = "This Site"
disqusShortname = "dev-learning"
[params]
  afterDomain='ms'
  site_title = "polodev"
  site_description = "Learning With Ease"
[taxonomies]
  category="categories"
  tag="tags"
  author="authors"
  tutorial="tutorials"
  bit="bits"
  tutorialType="tutorialTypes"
  [outputs]
home = [ "HTML", "RSS", "JSON"]
[menu]
  [[menu.main]]
    identifier = "home"
    name = "this is home page"
    title = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tutorials"
    title = "tutorials"
    url = "/tutorials/"
    weight = 2
  [[menu.main]]
    identifier = "bits"
    title = "bits"
    url = "/bits/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "this is about page"
    title = "about"
    url = "/about/"
    weight = 99

[related]

# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
threshold = 0

# To get stable "See also" sections we, by default, exclude newer related pages.
includeNewer = true

# Will lower case keywords in both queries and in the indexes.
toLower = false

[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name  = "author"
toLower = true
weight = 30
[[related.indices]]
name  = "tags"
weight = 200
[[related.indices]]
name  = "tutorials"
weight = 200
[[related.indices]]
name  = "bits"
weight = 200
[[related.indices]]
name  = "type"
weight = 1000

